### ISSUE TITLE
Not Launching on Windows

### ISSUE THREAD

**Issue by beaudown** [scala-network/XLArig#21]
No Gui or anything launches on windows. Maybe a security problem had to manually allow download because windows kept flagging as virus. After getting the zip with a system file and a program unzipped and launched nothing happens.

**Comment by treneth333** [comment]
Sometimes one can boot the device into safe mode allowing all the base files to load.
While in safe mode test different interactive parts of the GUI, if there is no error it may have fixed it.

If not, there's the option to refresh the PC and perform a check disk operation.

If all else fails the OS it's self may need to be re-installed.

**Comment by Teredic** [comment]
please exclude the directory or the file from your antivirus to be able to mine.

And i just released a new version, perhaps this one will works better.
