### ISSUE TITLE
Can not execute scripts/build_deps.sh

### ISSUE THREAD

**Issue by Polensky** [scala-network/XLArig#26]
When running build_deps.sh i get the following:
```
> ./build_deps.sh
: invalid option
```
So i started investigating and found out the file had DOS line ending which we can see by using the command `cat -v build_deps.sh` which give:
```
#!/bin/bash -e^M
^M
./build.uv.sh^M
./build.hwloc.sh^M
./build.openssl.sh% 
```
Each `^M` is a DOS line ending. To fix this, i used  the following command:
```
grep -URL ^M . | xargs dos2unix
```

**Comment by Teredic** [comment]
i don't understand how it has been converted to dos, but i've made the changes to CF (Unix)
