### ISSUE TITLE
Segmentation fault on Raspberry Pi 3

### ISSUE THREAD

**Issue by vanga83** [scala-network/XLArig#28]
I keep getting segmentation fault on my Raspberry Pi 3. Switching to a new SD card does the same thing. Majority of the time it'll have a segmentation fault and a very small chance of it actually starting. I thought it might be just my Pi not building it correctly but when I tried xmrig for Monero, it starts up perfectly each time. This didn't happen before with v5.2.0 and older. Would it be due to not having AES on the Pi? I also have a Nanopi Neo2 and it works perfectly there each time I start it up. I've tried this on the no longer in use Cxcore Ubuntu 18.04 64 bit, official Ubuntu 20.04 64 bit, and Raspberry Pi OS 64 bit Beta which all came out with the same results.

* ABOUT        XLArig/5.2.1 gcc/10.1.0
 * LIBS         libuv/1.18.0 OpenSSL/1.1.1
 * HUGE PAGES   supported
 * 1GB PAGES    unavailable
 * CPU          ARM Cortex-A53 (1) 64-bit -AES
                threads:4
 * MEMORY       0.2/0.9 GB (19%)
 * DONATE       0%
 * POOL #1      mine.scalaproject.io:3333 algo panthera
 * COMMANDS     hashrate, pause, resume, results, connection
[2021-02-11 17:39:19.200]  net      use pool mine.scalaproject.io:3333  XX.XXX.XXX.XXX
[2021-02-11 17:39:19.201]  net      new job from mine.scalaproject.io:3333 diff 500 algo panthera height 139534
[2021-02-11 17:39:19.201]  cpu      use argon2 implementation default
[2021-02-11 17:39:20.401]  randomx  init dataset algo panthera (4 threads) seed 0125b28b3be89e08...
[2021-02-11 17:39:20.401]  randomx  not enough memory for RandomX dataset
[2021-02-11 17:39:20.401]  randomx  failed to allocate RandomX dataset, switching to slow mode (0 ms)
Segmentation fault

**Comment by woodycal** [comment]
Try the following.

Sudo apt-get install -y raspbian-nspawn-64

Enter the 64bit shell with following command:

ds64-shell

Once in shell go ahead and install XLArig as per build instructions but change the cmake part to: 

cmake ..

Your most likely getting this error because either your installing it in 32bit os or cmake option.

Any problems jump over to their discord.

**Comment by vanga83** [comment]
I saw that before and tried installing it but it doesn't install in a 64 bit OS since all I have are 64 bit OSes which gives better performance.

I'll try again when I have time with the cmake.

**Comment by vanga83** [comment]
Sadly, still the same issue.

**Comment by woodycal** [comment]
Hi 

I did some testing yesterday and their is a Segmentation fault when running XLArig with a device with less then 4 gb ram in the current version of xlarig. Until they update xlarig you can try version XLArig 5.1.0 which i tested works on a nanopi fire 3.

Also this is a guide to install on rapsberry pi https://github.com/israel-p-s/Scala/blob/main/HowToMineWithRPI.md

**Comment by vanga83** [comment]
Thanks for the quick response! Weird though since my Nanopi Neo2 only has 512MB of RAM and it works perfectly fine there each time it starts up and it's running Armbian. Would it be due to the kernel provided for the OSes that I have for the Raspberry Pi 3? I only use 64 bit OSes for the Raspberry Pi.

I think the guide you linked is for 32 bit Raspbian/Raspberry Pi OS only but I could go that route. I was on 5.2.0 previously and didn't have any issues on that version. I'll roll back the prior versions to see if I still have problems.

**Comment by woodycal** [comment]
It could well be related to os also but considering i got a segmentation fault on my nanopi fire 3 which also is running an armbian os says that the bug from xmrig https://github.com/xmrig/xmrig/issues/1825 has come through to xlarig. Until they do a new version with lastest xmrig pull anyone with less then 4gb ram will encounter weird errors.

**Comment by vanga83** [comment]
I didn't get any errors on cmake that I noticed. Let me run both ways with and without the options and put it on here. Give me some time to run it.

**Comment by vanga83** [comment]
I still had my ssh terminal window open and it had all the things I did with and without the cmake options.

pi@rpi303:~/XLArig/build $ cmake .. -DXMRIG_DEPS=scripts/deps -DBUILD_STATIC=ON
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Use ARM_TARGET=8 (aarch64)
-- Performing Test XMRIG_ARM_CRYPTO
-- Performing Test XMRIG_ARM_CRYPTO - Success
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Found UV: /home/pi/XLArig/scripts/deps/lib/libuv.a
-- Looking for __builtin___clear_cache
-- Looking for __builtin___clear_cache - found
-- WITH_MSR=OFF
-- Found OpenSSL: /home/pi/XLArig/scripts/deps/lib/libcrypto.a (found version "1.1.1i")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/XLArig/build



pi@rpi303:~/XLArig/build $ cmake ..
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Use ARM_TARGET=8 (aarch64)
-- Performing Test XMRIG_ARM_CRYPTO
-- Performing Test XMRIG_ARM_CRYPTO - Success
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Found UV: /usr/lib/aarch64-linux-gnu/libuv.a
-- Looking for __builtin___clear_cache
-- Looking for __builtin___clear_cache - found
-- WITH_MSR=OFF
-- Found OpenSSL: /usr/lib/aarch64-linux-gnu/libcrypto.so (found version "1.1.1d")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/XLArig/build

**Comment by woodycal** [comment]
should be cmake .. with no flags as per xmrig instructions. Also are you deleting xlarig folder when your rebuilding ?

**Comment by vanga83** [comment]
Yes, I delete the entire XLArig folder and start over.

**Comment by vanga83** [comment]
I've switched to v5.1.0 for now like you mentioned and it's working again. Thank you so much for your help! I'll wait until next updated version to test out if there are any problems.

**Comment by woodycal** [comment]
> I've switched to v5.1.0 for now like you mentioned and it's working again. Thank you so much for your help! I'll wait until next updated version to test out if there are any problems.

Just out of interest did you install this on the 32bit os in the 64bit shell or just used to 64bit beta raspbian os without the 64bit shell command?

**Comment by vanga83** [comment]
> > I've switched to v5.1.0 for now like you mentioned and it's working again. Thank you so much for your help! I'll wait until next updated version to test out if there are any problems.
> 
> Just out of interest did you install this on the 32bit os in the 64bit shell or just used to 64bit beta raspbian os without the 64bit shell command?

I just used the 64 bit beta without the shell command.

**Comment by woodycal** [comment]
> Hi, i just compiled a beta build of xlarig 5.2.2 for armV8 : [xlarig522-armv8_beta.zip](https://github.com/scala-network/XLArig/files/5977483/xlarig522-armv8_beta.zip)
> 
> Could you please try it and tell me if you get a seg fault ?

Still error posted screen shot in discord

**Comment by Teredic** [comment]
the building instructions for RPis has been included, and the next armv8 build will be compiled that way too.
