### ISSUE TITLE
XLArig  v5.2.1 doesn't work on Windows 10

### ISSUE THREAD

**Issue by TannerSutherlin** [scala-network/XLArig#33]
When I run the program it quickly comes up with a cmd prompt screen and closes out. No error messages.

I've run the program as administrator and set an exclusion on windows security settings. I've also tried to turn off my Anti Virus altogether but nothing seems to work to get it to run. 

Does anyone know any solutions/workarounds?

**Comment by Teredic** [comment]
please put this into the 1st line on your script : `@cd /d "%~dp0"`

It tells windows to go to the directory where the script is launched instead of `C:\Windows\system32`. 

That way you can run it as admin.

**Comment by TannerSutherlin** [comment]
That didn't work either. It still just quickly pops up and goes away. I've configured a start.bat file where I put my wallet and pool address in.

This is what it looks like (I took my wallet address out):
@cd /d "%~dp0"
xlarig.exe --donate-level 1 -o pool.scala.herominers.com:10131 -u 
-wallet address -p DesktopRig -a panthera -k
pause

**Comment by Teredic** [comment]
your script should work like this : 
i don't know what the `-k` argument does but it's not necessary
``@cd /d "%~dp0"
xlarig.exe --donate-level 1 -o -pool scala.herominers.com:10131 -u wallet_address -p DesktopRig -a panthera
pause``

**Comment by TannerSutherlin** [comment]
Interesting, it's working now. I guess I just had to put the pool address with adding the -pool in front of it. Thanks!

**Comment by Teredic** [comment]
no problem ;)
