### ISSUE TITLE
C:\Users\krazy\Downloads>xlarig.exe -o mine.scalaproject.io:3333 -p maez001 -u SvmeZVRqEFN8C7cDcTN9sGJzn6PVeXbp6RZMFRNnBNqUSG1fs7Zo9WLbmiwZphG7M9TCvv1MxJm6N8C9hBPF2q2y1J4Sr1pUU --donate-level 1 -a panthera -k 'xlarig.exe' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by krazymaez6** [scala-network/XLArig#37]
i keep trying and not getting past this point

**Comment by krazymaez6** [comment]
i am trying to mine my laptop with xlarig have windows 10

**Comment by Teredic** [comment]
it means it doesn't find the executable. Please check it hasn't been deleted by your AV.

**Comment by krazymaez6** [comment]
how i really want to do this

**Comment by krazymaez6** [comment]
ok i fillally was able to run andhookup contributed pool shars yes! but i was wonding how to get the msr to work to mine more efficcently
