### ISSUE TITLE
Segmentation fault (core dumped) when starting xlarig

### ISSUE THREAD

**Issue by sascha08-15** [scala-network/XLArig#38]
Ubuntu 20.10 running

Executing the xlarig 5.2.2 receives: Segmentation fault (core dumped) when starting xlarig

My suspicions: are you trying to use/set wrsmr? Not executing as root (obviously, and not planning to do so).

Any advices?

**Comment by Teredic** [comment]
Could you please tell me what kind of cpu you are using ?

**Comment by boner-cmd** [comment]
From the build instructions:

> Since Raspbian is a 32 bit OS and XLArig is a 64 bit miner, you'll need to be on a 64-bit container if you don't want to get a segmentation fault after starting it.

Any chance you're on a 32 bit OS?

**Comment by sascha08-15** [comment]
Thanks for the reply. Yes sure. I am using an Intel 9900k

**Comment by sascha08-15** [comment]
It's 64 bit for sure. Kernel 5.8.0-50-generic

**Comment by ViralWeaponry** [comment]
Im also having this issue but I'm on a VM with Ubuntu on a Ryzen 5 laptop

**Comment by Teredic** [comment]
Could you please try this build i just made : https://github.com/scala-network/XLArig/releases/download/v5.2.2/XLArig-v5.2.2-linux-x86_64_alt.zip ?

**Comment by ViralWeaponry** [comment]
Hi,

Thank you! I just tried it but got the same error. I am using a VM in
VirtualBox but I was able to run xmrig without issues, I'm guessing this
miner is similar, please correct me if I'm wrong.

[image: image.png]

Sincerely,

Inartaly Valentin

**Comment by Teredic** [comment]
Ok. I created a cleaned VM under Ubuntu 20.04 and here's the result : 

https://github.com/scala-network/XLArig/releases/download/v5.2.2/XLArig-v5.2.2-linux-x86_64_v3.zip

Does it work with this build ?

**Comment by ViralWeaponry** [comment]
Yes it does! Thank you for your help and time. Much appreciated.

Sincerely,

Inartaly Valentin

**Comment by boner-cmd** [comment]
@sascha08-15 did the VM build help? Also, are there any other messages? When setting up mine on 20.10 any time I had bad configuration options it would seg fault. Even things like an incorrect pool port. Is there something above the seg fault to give more info?

**Comment by ViralWeaponry** [comment]
Teredic reached out to me and fixed the issue with a new build.

Thank you,

Inartaly Valentin

**Comment by boner-cmd** [comment]
I was asking Sascha, the original poster who opened the issue 😅 and who wasn't necessarily using a VM to experience it

**Comment by ViralWeaponry** [comment]
sorry, i got confused, for some reason I got an email with your question.  :)

**Comment by sascha08-15** [comment]
Nice! Yes, the VM build works like a charm! May I ask, what did you change in the codebase?

**Comment by Teredic** [comment]
> 
> 
> Nice! Yes, the VM build works like a charm! May I ask, what did you change in the codebase?

Nothing. I compiled the same way, as I usually do. However all my previous build were compiled under Debian 10, so perhaps there's a bug somewhere.
