### ISSUE TITLE
Apple M1 silicon

### ISSUE THREAD

**Issue by Verminous** [scala-network/XLArig#39]
Will there be support for mining on Apple M1 silicon macs?

**Comment by Teredic** [comment]
support is technically added, but since it requires a M1 cpu to compile the binary, i wasn't able to do (and test) it yet.

I could give you the steps to compile by yourself if you want...

**Comment by ahmyi** [comment]
You can try the x86 mac osx [build]( https://github.com/scala-network/XLArig/releases/download/v5.2.2/XLArig-v5.2.2-macOS-x86_64.zip) it works with m1

**Comment by Drigtime** [comment]
Of course it works with the x86 build, it's thanks to Rosetta 2, but it's not optimal, it's like mining on a VM instead of the local machine directly.

@Teredic Could you give us the instruction to build the M1 version please ?

**Comment by Teredic** [comment]
Of course !

First you'll need to install brew. The command is indicated on this site : https://brew.sh/

Then here's the set of commands to compile the miner : 

```
1. brew install cmake libuv openssl hwloc
2. git clone --recursive https://github.com/scala-network/xlarig
3. mkdir xlarig/build && cd xlarig/build
4. cmake .. -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl
5. make -j$(sysctl -n hw.logicalcpu)
```
