### ISSUE TITLE
tested on ubuntu. 

### ISSUE THREAD

**Issue by SuperCDN** [scala-network/XLArig#44]
what do I have to do? not usually this happens when i use cpuminer-opt-cpu-pool, but when i want to try something new it happens.

`./xlarig: error while loading shared libraries: libhwloc.so.15: cannot open shared object file: No such file or directory`
`./xlarig: error while loading shared libraries: libuv.so.1: cannot open shared object file: No such file or directory`
tested on ubuntu.

**Comment by NotRealPaz** [comment]
have you install ``libhwloc-dev`` and ``libuv1-dev``?
