### ISSUE TITLE
compiling XLArig in msys2 fails

### ISSUE THREAD

**Issue by builder2020** [scala-network/XLArig#5]
when using msys2 to compile in windows it fails at:

Building CXX object defyx/CMakeFiles/defyx.dir/src/virtual_memory.cpp.obj

C:/msys64/home/XLArig/defyx/src/virtual_memory.cpp: In function 'void setPrivilege(const char*, BOOL)':
C:/msys64/home/XLArig/defyx/src/virtual_memory.cpp:65:34: error: cannot convert 'const char*' to 'LPCWSTR' {aka 'const wchar_t*'}
   65 |  if (!LookupPrivilegeValue(NULL, pszPrivilege, &tp.Privileges[0].Luid))
      |                                  ^~~~~~~~~~~~
      |                                  |
      |                                  const char*
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:70,
                 from C:/msys64/home/XLArig/defyx/src/virtual_memory.cpp:34:
C:/msys64/mingw64/x86_64-w64-mingw32/include/winbase.h:2365:81: note:   initializing argument 2 of 'WINBOOL LookupPrivilegeValueW(LPCWSTR, LPCWSTR, PLUID)'
 2365 |   WINADVAPI WINBOOL WINAPI LookupPrivilegeValueW (LPCWSTR lpSystemName, LPCWSTR lpName, PLUID lpLuid);
      |                                                                         ~~~~~~~~^~~~~~
make[2]: *** [defyx/CMakeFiles/defyx.dir/build.make:128: defyx/CMakeFiles/defyx.dir/src/virtual_memory.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:163: defyx/CMakeFiles/defyx.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by Teredic** [comment]
you just need to comment (or remove) the lines 65 and 66 of that file : C:/msys64/home/XLArig/defyx/src/virtual_memory.cpp ;)

**Comment by builder2020** [comment]
deleting lines 65 and 66 allowed it to progress, but then it error'd out at some subsequent points in yescrypt-platform.c, i just deleted those lines also and eventually it compiled :) thanks!

**Comment by BKdilse** [comment]
Was it only yescrypt-platform.c you had to delete from, or others too?

I've got a similar issue, but deleting from yescrypt-platform.c still errors.

**Comment by Teredic** [comment]
if it's the "mman.h" error, just change the line 21 (or 22?), and replace "#include <sys/mman.h>" by these three lines :

#ifdef __linux__
#include <sys/mman.h>
#endif

**Comment by builder2020** [comment]
Yeah there was another subsequent error after the sys/mman.h, but my amateur approach was just delete any lines that caused errors and eventually it worked. I can go back through it and post each one if it helps? But it's probably better if teredic or another professional just tries compiling and posts the correct edits to make / changes the code that's available to be pulled

**Comment by builder2020** [comment]
re-ran the compile after making the change to sys/mman.h, here is the following error: 

C:/msys64/home/XLArig/defyx/src/blake2/yescrypt-platform.c:81:11: error: 'ENOMEM' undeclared (first use in this function)
   81 |   errno = ENOMEM;
      |           ^~~~~~
C:/msys64/home/XLArig/defyx/src/blake2/yescrypt-platform.c:81:11: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [defyx/CMakeFiles/defyx.dir/build.make:414: defyx/CMakeFiles/defyx.dir/src/blake2/yescrypt-platform.c.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:163: defyx/CMakeFiles/defyx.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by builder2020** [comment]
When removed that 'errno = ENOMEM line' the code then compiles and the executable is available to be used but there is an error in one of the tests: affinity.cpp.obj that may or may not be important?

[100%] Building CXX object defyx/CMakeFiles/defyx-benchmark.dir/src/tests/affinity.cpp.obj
C:/msys64/home/XLArig/defyx/src/tests/affinity.cpp: In function 'int set_thread_affinity(const unsigned int&)':
C:/msys64/home/XLArig/defyx/src/tests/affinity.cpp:48:77: error: invalid static_cast from type 'HANDLE' {aka 'void*'} to type 'std::thread::native_handle_type' {aka 'long long unsigned int'}
   48 |     thread = static_cast<std::thread::native_handle_type>(GetCurrentThread());
      |                                                                             ^
C:/msys64/home/XLArig/defyx/src/tests/affinity.cpp: In function 'int set_thread_affinity(std::thread::native_handle_type, const unsigned int&)':
C:/msys64/home/XLArig/defyx/src/tests/affinity.cpp:67:58: error: invalid static_cast from type 'std::thread::native_handle_type' {aka 'long long unsigned int'} to type 'HANDLE' {aka 'void*'}
   67 |     rc = SetThreadAffinityMask(static_cast<HANDLE>(thread), 1ULL << cpuid) == 0 ? -2 : 0;
      |                                                          ^
make[2]: *** [defyx/CMakeFiles/defyx-benchmark.dir/build.make:76: defyx/CMakeFiles/defyx-benchmark.dir/src/tests/affinity.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:244: defyx/CMakeFiles/defyx-benchmark.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
