### ISSUE TITLE
XLArig/5.2.1 Armbian DNS error: "no address"

### ISSUE THREAD

**Issue by mvmagalhaes** [scala-network/XLArig#50]
could anyone help with this error in the arm version?

XLArig-v5.2.1-linux-arm_armv7.zip
![Screen Shot 2022-04-23 at 10 36 55 PM](https://user-images.githubusercontent.com/44643533/164952024-6ca448a2-556f-4725-9034-bd91028ecde8.png)

**Comment by mvmagalhaes** [comment]
./xlarig --donate-level 1 -o scala.herominers.com:10131 -u Ssy2XFLFGJhSegvi1AJKRF9VZ69Gwmv1GcNvsod35Y7JagdvjAGLFq4h6J3YoJiWyyQKCFZb77kRmfZ8Uc51CFzx5kXVwBNmKx -p rk322x -a panthera -k

**Comment by ahmyi** [comment]
You have to use an ip address if dns doesn't detect
