### ISSUE TITLE
Can't run Xlarig miner on Ubuntu (Linux)

### ISSUE THREAD

**Issue by TheCat4256** [scala-network/XLArig#51]
I downloaded it from Github website and I set up the miner.
I tried running it with sudo ./xlarig and it won't run. I get an error. Any ideas?

**Comment by NotRealPaz** [comment]
what's your error / system / config?

**Comment by 57u** [comment]
On a fresh Ubuntu VPS:

./xlarig 
./xlarig: error while loading shared libraries: libhwloc.so.15: cannot open shared object file: No such file or directory
