### ISSUE TITLE
Error: Need update OpenSSL version

### ISSUE THREAD

**Issue by J9B10** [scala-network/XLArig#55]
Hello

XLArig does not run on Garuda Linux (Arch Linux).

```
Error:
./xlarig: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

XLArig requires the `openssl` library `libssl.so.1.1`.
But this version `1.1` is not in the system as it is a version **abandoned** by OpenSSL.

The **latest** version of the Operating System (**Compatible**) is:

`openssl 3.1.4`

and can be found at:
`/usr/lib/libssl.so`

XLArig needs to be updated to be compatible.

Terminal image ERROR:
![With ERROR:](https://github.com/scala-network/XLArig/assets/98818736/14fe7602-cfdb-490b-80d2-1f19229ca875)

**Comment by Teredic** [comment]
Hello,

Thanks for the report.

Could you tell me if you downloaded xlarig from the release section, or if you tried to build it yourself ?

**Comment by J9B10** [comment]
I used binary [XLArig-v5.2.3-linux-x86_64.zip](https://github.com/scala-network/XLArig/releases/download/v5.2.3/XLArig-v5.2.3-linux-x86_64.zip) what is on the page [XLArig/releases](https://github.com/scala-network/XLArig/releases).

**Comment by Teredic** [comment]
here's a build with the latests dependencies. Could you tell me if this one work ?
[xlarig-v5.2.4-linux-x86_64_build1.zip](https://github.com/scala-network/XLArig/files/13660068/xlarig-v5.2.4-linux-x86_64_build1.zip)

**Comment by J9B10** [comment]
> here's a build with the latests dependencies. Could you tell me if this one work ? [xlarig-v5.2.4-linux-x86_64_build1.zip](https://github.com/scala-network/XLArig/files/13660068/xlarig-v5.2.4-linux-x86_64_build1.zip)

Yes. I tested it.
Worked perfectly.
Now it's ok. 👍

Terminal image OK:
![OK](https://github.com/scala-network/XLArig/assets/98818736/8315088c-01c6-457e-a8fd-4179fb53dc04)

**Comment by J9B10** [comment]
Hello!

When will this fix be released in an official downloadable binary?

**Comment by Teredic** [comment]
hi ! it will be released this saturday ;)
