### ISSUE TITLE
need rebuild from v311, stdout log bug fixed

### ISSUE THREAD

**Issue by qutimqqcom** [scala-network/XLArig#7]

**Comment by qutimqqcom** [comment]
got it, close

**Comment by qutimqqcom** [comment]
311 mo1 ocean  not  support xla

**Comment by qutimqqcom** [comment]
now work around
"log-file": "/dev/null",

**Comment by unsivilaudio** [comment]
If you are on ubuntu I have compiled releases, I've merged xmrig's commit to fix this into my own [repo.](https://github.com/unsivilaudio/XLArig/releases/tag/3.1.0)  Seems to be working.
