### ISSUE TITLE
Error during "make" - Need kind help pls. Lubuntu here.

### ISSUE THREAD

**Issue by d0n-miner1** [scala-network/XLArig#8]
parez@parez:~/Downloads/XLArig/build$ make
Scanning dependencies of target argon2
[  0%] Building C object src/3rdparty/argon2/CMakeFiles/argon2.dir/lib/argon2.c.o
[  1%] Building C object src/3rdparty/argon2/CMakeFiles/argon2.dir/lib/core.c.o
[  2%] Building C object src/3rdparty/argon2/CMakeFiles/argon2.dir/lib/encoding.c.o
[  3%] Building C object src/3rdparty/argon2/CMakeFiles/argon2.dir/lib/genkat.c.o
[  4%] Building C object src/3rdparty/argon2/CMakeFiles/argon2.dir/lib/impl-select.c.o
[  4%] Building C object src/3rdparty/argon2/CMakeFiles/argon2.dir/lib/blake2/blake2.c.o
[  5%] Building C object src/3rdparty/argon2/CMakeFiles/argon2.dir/arch/generic/lib/argon2-arch.c.o
[  6%] Linking C static library libargon2.a
[  6%] Built target argon2
Scanning dependencies of target xlarig
[  7%] Building CXX object CMakeFiles/xlarig.dir/src/backend/cpu/CpuLaunchData.cpp.o
[  8%] Building CXX object CMakeFiles/xlarig.dir/src/base/io/Console.cpp.o
[  8%] Building CXX object CMakeFiles/xlarig.dir/src/base/io/json/Json.cpp.o
[  9%] Building CXX object CMakeFiles/xlarig.dir/src/base/io/json/JsonChain.cpp.o
[ 10%] Building CXX object CMakeFiles/xlarig.dir/src/base/io/json/JsonRequest.cpp.o
[ 11%] Building CXX object CMakeFiles/xlarig.dir/src/base/io/log/backends/ConsoleLog.cpp.o
[ 12%] Building CXX object CMakeFiles/xlarig.dir/src/base/io/log/backends/FileLog.cpp.o
[ 12%] Building CXX object CMakeFiles/xlarig.dir/src/base/io/log/Log.cpp.o
[ 13%] Building CXX object CMakeFiles/xlarig.dir/src/base/io/Watcher.cpp.o
[ 14%] Building CXX object CMakeFiles/xlarig.dir/src/base/kernel/Base.cpp.o
In file included from /home/parez/Downloads/XLArig/src/core/config/Config.h:34:0,
                 from /home/parez/Downloads/XLArig/src/base/kernel/Base.cpp:40:
/home/parez/Downloads/XLArig/src/core/Benchmark.h:55:24: error: ‘CN_GPU’ is not a member of ‘xlarig::Algorithm’
             Algorithm::CN_GPU,
                        ^~~~~~
cc1plus: warning: unrecognized command line option ‘-Wno-class-memaccess’
CMakeFiles/xlarig.dir/build.make:278: recipe for target 'CMakeFiles/xlarig.dir/src/base/kernel/Base.cpp.o' failed
make[2]: *** [CMakeFiles/xlarig.dir/src/base/kernel/Base.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/xlarig.dir/all' failed
make[1]: *** [CMakeFiles/xlarig.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
parez@parez:~/Downloads/XLArig/build$

**Comment by d0n-miner1** [comment]
parez@parez:~/Downloads/build$ uname -na
Linux parez 4.15.0-62-generic #69-Ubuntu SMP Wed Sep 4 20:55:37 UTC 2019 i686 athlon i686 GNU/Linux

**Comment by ahmyi** [comment]
Try this
```mkdir build```
```cd build```
```cmake ..```
```make -j`nproc` ```
