### ISSUE TITLE
Linux issue: no valid config.json file(manjaro)

### ISSUE THREAD

**Issue by senkivalaki** [scala-network/XLArig#9]
I was trying to set up this miner, and after a bit of trying, I have successfully got the computer to build the program successfully, but, when I tried to run it, it just returned no valid configuration found, exiting, despite the fact that I was running it with the arguments I needed typed right into the command line. I need some help, because I couldn't really find any instructions on this at all.
Thanks for your help!

**Comment by CryptoFrancoQc** [comment]
Can you try this config file? Just change the extension to .json
[config.txt](https://github.com/scala-network/XLArig/files/3637197/config.txt)
